"""intelligence_pipeline"""
from alembic import op
import sqlalchemy as sa

revision = '0cff59a89d4b'
down_revision = 'a8552c328d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('rule_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('product_category', sa.String(length=120), nullable=True),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('validator_type', sa.String(length=30), nullable=False),
    sa.Column('validator_config', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_document', sa.String(length=500), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo_or_provisional', sa.Boolean(), nullable=False),
    sa.CheckConstraint("validator_type IN ('required','regex','numeric','date','comparison','conditional_required')", name='ck_rule_validator'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', 'version', name='uq_rule_version')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('inspection_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("overall_status IN ('COMPLIANT','NON_COMPLIANT','REVIEW_REQUIRED')", name='ck_analysis_overall'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_overall_status'), ['overall_status'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('inspection_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('analysis_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('image_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('image_side', sa.String(length=10), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('raw_value', sa.String(length=4000), nullable=False),
    sa.Column('normalized_value', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('source_text', sa.String(length=4000), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('image_processing',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('inspection_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('image_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('pipeline_version', sa.String(length=30), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("quality IN ('GOOD','LOW_QUALITY','UNREADABLE')", name='ck_processing_quality'),
    sa.CheckConstraint("status IN ('success','failed')", name='ck_processing_status'),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    with op.batch_alter_table('image_processing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_processing_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('ocr_results',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('inspection_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('image_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_ocr_confidence'),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_results_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocr_results_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('rule_evaluations',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('inspection_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('analysis_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('rule_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('evidence_field_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('rule_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PASS','FAIL','REVIEW')", name='ck_rule_evaluation_status'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_field_id'], ['extracted_fields.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_evaluations_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_evaluations_inspection_id'), ['inspection_id'], unique=False)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_id', sa.Uuid(as_uuid=False), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_foreign_key('fk_reports_analysis_id', 'analysis_runs', ['analysis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_reports_analysis_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_analysis_id'))
        batch_op.drop_column('analysis_id')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_column('processing_started_at')
        batch_op.drop_column('processing_token')

    with op.batch_alter_table('rule_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_evaluations_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_rule_evaluations_analysis_id'))

    op.drop_table('rule_evaluations')
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_results_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_ocr_results_image_id'))

    op.drop_table('ocr_results')
    with op.batch_alter_table('image_processing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_processing_inspection_id'))

    op.drop_table('image_processing')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_name'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_analysis_id'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_overall_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_created_at'))

    op.drop_table('analysis_runs')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
